title: Bouw een webpagina
hero_image: images/banner.png
description: Bouw een webpagina over iets dat je wilt delen.
meta_title: Leer webontwikkeling voor beginners | Bouw een webpagina
meta_description: Leer webontwikkeling voor beginners met de Raspberry Pi Foundation. Bouw een webpagina met verschillende HTML-elementen. Voeg CSS-klassen toe om jouw pagina te stylen.
version: 4
listed: true
copyedit: true
last_tested: "2021-03-26"
steps:
  - 
    title: Inleiding
  - 
    title: Jouw onderwerp
  - 
    title: Bouw en test
    completion: engaged
  - 
    title: Deel
    completion: internal
  - 
    title: Reflectie
    completion: external
  - 
    title: Verbeter je project
  - 
    title: Wat kun je verder nog doen?
