title: Build a webpage
hero_image: images/banner.png
description: Build a webpage about something you want to share.
pdf: resources/rpfi-build-a-webpage.pdf
meta_title: Learn web development for beginners | Build a webpage
meta_description: Learn web development for beginners with the Raspberry Pi Foundation. Build a webpage with a variety of HTML elements. Add CSS classes to style your page.
version: 4
listed: true
copyedit: true
last_tested: "2021-03-26"
steps:
  - title: Introduction
  - title: Your topic
  - title: Build and test
    completion: engaged
  - title: Share
    completion: internal
  - title: Reflection
    completion: external
  - title: Upgrade your project
