title: Créer une page web
hero_image: images/banner.png
description: Crée une page web sur quelque chose que tu souhaites partager.
meta_title: Apprendre le développement web pour les débutants | Créer une page web
meta_description: Apprends le développement web pour les débutants avec la Raspberry Pi Foundation. Crée une page web avec une variété d'éléments HTML. Ajoute des classes CSS pour styliser ta page.
version: 4
listed: true
copyedit: true
last_tested: "2021-03-26"
steps:
  - 
    title: Introduction
  - 
    title: Ton sujet
  - 
    title: Créer et tester
    completion: engaged
  - 
    title: Partager
    completion: internal
  - 
    title: Réflexion
    completion: external
  - 
    title: Améliorer ton projet
  - 
    title: Et ensuite ?
